import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
 FilterPageMainContainer:{
  width:'100%',
  height:'auto',
  marginBottom:180
 },
 FilterPageContainer:{
  display:'flex',
  flexDirection:'row',
  gap:10,
  minHeight:50,
  paddingHorizontal:10,
  paddingVertical:15,
  marginTop:10,
  borderWidth:1,
  borderColor:'gold',
  backgroundColor:'rgba(0,0,0,0.07)',
 },
 FilterChildMainContainer:{
  width:'100%',
  height:'100%',
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
 },
 FilterChildHeadContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  gap:2,
  borderRightWidth:1.2,
  paddingHorizontal:7,
  position:'relative'
 },
 FilterChildHeadText:{
  fontSize:11,
  fontWeight:'500',
  textAlign:'center',
 },
 FilterChildHeadImage:{
  width:12,
  height:12
 },

                            // BODY

 FilterPageBodyMainContainer:{
  width:'100%',
  height:'auto',
  alignItems:'center',
  gap:20
 },
 FilterPageUniContainer:{
  width:'97%',
  maxWidth:500,
  height:'auto',
  backgroundColor:'rgba(0,0,100,0.05)',
  marginTop:5,
  paddingVertical:10,
 },
 FilterPageUniHeaderContainer:{
  flexDirection:'column',
  width:'auto'
 },
 FilterPageUniHeaderNameContainer:{
  paddingHorizontal:15,
  paddingVertical:15
 },
 FilterPageUniHeaderNameText:{
  fontSize:15,
  fontWeight:'500',
  color:'lightblue',
  letterSpacing:0.3
 },
 FilterBothContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  justifyContent:'flex-start',
  paddingLeft:'5%',
  gap:10,
  borderBottomWidth:1.5,
  borderColor:'lightblue',
  borderStyle:'dashed',
  paddingBottom:20
 },
 FilterPageUniHeaderLocationContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  gap:5,
  paddingRight:7,
  borderRightWidth:1.5,
  borderColor:'#888'
 },
 FilterPageUniHeaderLocationImage:{
  width:15,
  height:19,
 },
 FilterPageUniHeaderLocationText:{
  fontSize:12,
  fontWeight:'500'
 },
 FilterPageUniHeaderRatingContainer:{
  display:'flex',
  flexDirection:'row',
  paddingRight:5,
  alignItems:'center',
  borderRightWidth:1.5,
  borderColor:'#888'

 },
 FilterPageUniHeaderRatingImageContainer:{
  flexDirection:'row',
  gap:0,
 },
 FilterPageUniHeaderRateText:{
  fontSize:11,
  fontWeight:'bold',
  paddingLeft:5
 },
 FilterCourseFeesMainContainer:{
  width:'95%',
  alignSelf:'center',
  display:'flex',
  flexDirection:'row',
  justifyContent:'space-between',
  paddingVertical:10,
  borderBottomWidth:1.5,
  borderColor:'lightblue',
  borderStyle:'dashed'
 },
 FilterCourseFeesContainer:{
  gap:8,
  alignItems:'center'
 },
 FilterCourseFeesHeadText:{
  fontSize:15,
  fontWeight:'500',
  color:'#333',
  letterSpacing:1
 },
 FilterCourseFeesText:{
  fontSize:13,
  fontWeight:'500'
 },
 FilterAdmissionContainer:{
  display:'flex',
  flexDirection:'row',
  justifyContent:'flex-start',
  alignItems:'center',
  paddingLeft:'5%',
 },
 filterOptionMainContainer:{
  display:'none',
  width:'100%',
  height:'auto',
  position:'absolute',
  backgroundColor:'rgba(0,0,0,0.9)',
  zIndex:200,
  alignItems:'center',
  justifyContent:'space-around',
  padding:20,
  flexDirection:'row'
 },
 filterOptionContainer:{
  gap:10,
 },
 filterOptionBtnContainer:{
  borderColor:'lightblue',
  alignItems:'center',
  borderRadius:10,
  alignItems:'flex-start'
 },
 filterOptionBtnText:{
  fontSize:11,
  fontWeight:'500',
  color:'#cecece',
 }
})

export default styles