import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
 placesMainContainer:{
  width:'100%',
  height:'auto',
  paddingTop:20,
  marginBottom:60
 },
 placesHeadContainer:{
  width:'100%',
  alignItems:'flex-end'
 },
 placesHeadText:{
  width:'90%',
  textAlign:'right',
  alignSelf:'center',
  fontSize:20,
  fontWeight:'500',
  letterSpacing:0.5
 },
 placesBGImage:{
  width:'100%',
  height:200,
  resizeMode:'cover',
  marginTop:10,
  justifyContent:'flex-end',
  alignItems:'flex-end',
 },
 placesBGTextContainer:{
  paddingHorizontal:15,
  paddingVertical:8,
  backgroundColor:'rgba(120,100,110,0.19)',
  margin:10,
  borderRadius:10
 },
 placesBGText:{
  fontSize:12,
  fontWeight:'500',
  color:'#333',
  letterSpacing:0.5
 },
 placesBodyContainer:{
  width:'100%',
  marginTop:30,
  gap:20
 },
 UniversityBodyMainConatiner:{
  width:'90%',
  maxWidth:500,
  marginLeft:'5%',
  backgroundColor:'rgba(0,0,0,0.1)',
  paddingBottom:10,
  borderWidth:1
 },
 placesBodyHeadContainer:{
  width:'85%',
  alignSelf:'center',
 },
 placesBodyHeadText:{
  fontSize:13,
  fontWeight:'500'
 },
 UniversityImgContainer:{
  width:'100%',
  height:150,
 },
 UniversityImg:{
  width:'100%',
  height:'100%',
  resizeMode:'cover'
 },
 placesRateContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  justifyContent:'center',
  margin:10,
  paddingHorizontal:12,
  paddingVertical:5,
  backgroundColor:'lightblue',
  alignSelf:'flex-end',
  gap:5
 },
 placesRateText:{
  fontSize:12,
  fontWeight:'500'
 },
 placesRateStar:{
  width:20,
  height:20,
  resizeMode:'cover'
 },
 placesUnderNote:{
  width:'90%',
  paddingTop:10,
  alignSelf:'center',
  gap:10
 },
 placesUnderNoteText:{
  justifyContent:'space-around',
  display:'flex',
  flexDirection:'row',
 },
 downloadBtn:{
  width:'97%',
  marginTop:10,
  alignSelf:'center',
  borderWidth:2,
  borderColor:'lightblue',
  paddingVertical:10,
  borderRadius:10
 },
 downloadBtnText:{
  fontSize:13,
  fontWeight:'500',
  textAlign:'center'
 }
})

export default styles