import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
 overviewMainContainer:{
  width:'100%',
 },
 overviewHeadTitleContainer:{
  display:'flex',
  flexDirection:'row',
  marginLeft:"7%",
  gap:3,
  alignItems:'center'
 },
 overviewHeadImage:{
  width:30,
  height:30
 },
 overviewHeadTitle:{
  fontSize:14,
  fontWeight:'500',
  letterSpacing:0.5,
 },
 overviewSmallTextContainer:{
  width:'97%',
  paddingLeft:'3%',
  paddingVertical:11,
 },
 overviewSmall:{
  fontSize:12,
  fontWeight:'400',
  letterSpacing:0.6,
  lineHeight:21
 },
 tableMainContainer:{
  display:'flex',
  width:'97%',
  flexDirection:'row',
  justifyContent:'space-between',
  marginVertical:10,
  borderWidth:1,
  alignContent:'center',
  alignSelf:'center',
 },
 tableLeftContainer:{
  flex:0.6,
  borderRightWidth:1,
  paddingVertical:4,
  alignContent:'center'
 },
 tableRightContainer:{
  flex:0.4,
  paddingVertical:4,
  alignContent:'center'
 },
 tableTitle:{
  fontSize:15,
  fontWeight:"500",
  textAlign:'center',
 },
 rowOne:{
  paddingTop:5,
  borderTopWidth:1,
 },
 tableInnerText:{
  fontSize:12.5,
  fontWeight:'500',
  paddingLeft:'3%'
 },
 overviewFactContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  marginLeft:'4%',
  gap:11,
  marginTop:10
 },
 factListImage:{
  width:17,
  height:17
 },

 // admission Table Conatainer

 admissionTableContainer:{
  display:'flex',
  flexDirection:'row',
  width:500,
  borderWidth:1,
  justifyContent:'space-between',
  flex:1,
  marginHorizontal:5,
 },
 tableTitleContainer:{
  width:'100%',
  alignItems:'center',
 paddingVertical:5
 },
 tableBodyContainer:{
  borderTopWidth:1,
  width:'100%',
  gap:10,
  paddingBottom:10,
 },
 admissionTableOneContainer:{
  flex:0.45,
 },
 admissionTableTwoContainer:{
  borderLeftWidth:1,
  borderRightWidth:1,
  flex:0.275,
 },
 admissionTableThreeContainer:{
  flex:0.275,
 },
 tableListContainer:{
  borderTopWidth:1,
  height:37
 },
 tableTitle:{
  fontSize:15,
  fontWeight:'500',
  letterSpacing:0.3
 },
 tableList:{
  fontSize:12,
  textAlign:'left',
  paddingLeft:5,
  width:'100%',
  height:'100%',
 },

 // departmentMainContainer

 departmentMainContainer:{
  width:'100%',
  alignItems:'center',
  gap:13
 },
 departmentContainer:{
  width:'90%',
  flexDirection:'row',
  alignContent:'center',
  alignItems:'center',
  backgroundColor:'rgba(0,0,0,0.06)',
  paddingVertical:5
 },
 programsContainer:{
  borderBottomWidth:1,
  width:'100%'
 },
 departmentListImage:{
  width:20,
  height:20
 },
 departmentFacultyContainer:{
  width:'75%',
  display:'flex',
  flexDirection:'row',
  gap:5,
  alignItems:'center',
  backgroundColor:'rgba(100,0,200,0.06)',
  padding:5,
 },
 departmentistContainer:{
  width:"85%",
  gap:10
 },
 departments:{
  fontSize:14,
  fontWeight:'500'
 },
 faculties:{
  fontSize:13,
  fontWeight:'500'
 },
 programs:{
  fontSize:13,
  fontWeight:'400'
 },
 smallLine:{
  width:'100%',
  height:1.5,
  backgroundColor:'lightblue',
 }
})

export default styles