import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
 LogInMainContainer:{
  width:'100%',
  flex:1,
  alignItems:'center',
  justifyContent:'center',
  marginTop:50,
  gap:40
 },
 LogInContainer:{
  width:'100%',
  alignItems:'center',
  justifyContent:'center',
  gap:10
 },
 LogInWelcomeContainer:{
  width:'95%',
  alignItems:'center',
 },
 LogInWelcome:{
  fontSize:23,
  fontWeight:'bold',
  color:'#555',
  textAlign:'center'
 },
 LogInNote:{
  fontSize:12,
  fontWeight:'bold'
 },
 inputIcons:{
  width:20,
  height:20,
 },
 inputIconsContainer:{
  flexDirection:'row',
  alignItems:'center',
  gap:10,
  width:'90%',
  maxWidth:800,
  height:50,
  backgroundColor:'rgba(0,0,0,0.1)',
  paddingHorizontal:10,
  overflow:'hidden',
  borderRadius:5
 },
 logInBtn:{
  alignSelf:'flex-end',
  marginRight:20,
  width:'30%',
  borderWidth:2,
  paddingVertical:10,
  alignItems:'center',
  borderRadius:5,
  minWidth:120,
  maxWidth:200
 },
 logInBtnText:{
  fontSize:17,
  fontWeight:'bold'
 },
 logInSignUpContainer:{
  width:'80%',
  flexDirection:'row',
  gap:7
 },
 logInSignUpText:{
  fontSize:15,
  color:"#333"
 },
 logInSignUpBtnText:{
  color:'blue',
  fontSize:15
 },
 logInAsGuestContainer:{
  alignSelf:'center',
  marginTop:10
 },
 logInAsGuestText:{
  fontSize:15,
  fontWeight:'light',
  color:'midnightblue',
  textTransform:'capitalize'
 },
 LogInOptionsMainContainer:{
  width:'70%',
  gap:6
 },
 LogInOptionsContainer:{
  flexDirection:'row',
  gap:20,
  marginBottom:10
 },
 LogInOptionsMainText:{
  fontSize:15,
  fontWeight:'bold',
  marginBottom:4
 },
 LogInOptionsSubContainer:{
  paddingHorizontal:6,
  paddingVertical:3
 },
 LogInOptionsText:{
  fontSize:12,
  fontWeight:'bold',
  color:'blue'
 }
})

export default styles