import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
 MatchHomeMainContainer:{
  backgroundColor:'rgba(120,0,0,0.09)',
  width:'100%',
  height:'auto',
 },
 MatchHomeHeadContainer:{
  width:'90%',
  alignSelf:'center',
  paddingTop:20,
  paddingBottom:10
 },
 MatchHomeHeadText:{
  fontSize:14,
  fontWeight:'500',
 },
 MatchHomeCourseContainer:{
  width:'95%',
  alignSelf:'center'
 },
 MatchHomeCourseText:{
  fontSize:12,
  fontWeight:'400'
 },
 courseInput:{
  width:'90%',
  borderWidth:2,
  alignItems:'center',
  paddingVertical:5,
  paddingHorizontal:15,
  fontSize:13,
  marginVertical:10,
  fontWeight:'400',
  borderRadius:10,
  borderColor:'lightblue'
 },
 matchDisclaimer:{
  paddingVertical:10,
  width:'70%',
  alignSelf:'flex-end',
  alignItems:'flex-end',
  gap:4
 },
 matchDisclaimerTitle:{
  fontSize:13,
  fontWeight:'500'
 },
 matchDisclaimerText:{
  fontSize:11,
  fontWeight:'400'
 },
 coreContainer:{
  width:'95%',
  alignSelf:'center',
  maxWidth:500,
  gap:10,
  marginTop:20
 },
 coreText:{
  fontSize:14,
  fontWeight:'500',
  paddingLeft:20
 },
 coreTextMainContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  gap:20,
  borderWidth:1,
  alignContent:'center',
  borderRadius:10
 },
 coreTextContainer:{
  paddingVertical:10,
  paddingHorizontal:15,
  backgroundColor:'rgba(0,0,0,0.09)',
  borderTopLeftRadius:10,
  borderBottomLeftRadius:10,
  width:'70%'
 },
 coreMainText:{
  fontSize:13,
  fontWeight:'500'
 },
 gradeText:{
  fontSize:13,
  fontWeight:'500'
 },
 matchButton:{
  marginVertical:20,
  borderWidth:2,
  alignItems:'center',
  paddingVertical:10,
  alignSelf:'flex-end',
  paddingHorizontal:25,
  marginRight:20,
  borderRadius:10,
  backgroundColor:'rgba(0,0,0,0.08)'
 },
 matchButtonText:{
  fontSize:15,
  fontWeight:'500'
 },
 
 // match Universities Container

 matchUniversitiesContainer:{
  width:'100%',
 },
 matchUniversitiesHeaderContainer:{
  width:'90%',
  alignSelf:'center',
  maxWidth:500,
  paddingVertical:20
 },
 matchUniversitiesHeaderText:{
  fontSize:14,
  fontWeight:"500",
  letterSpacing:0.5
 },
 FilterPageUniContainer:{
  width:'97%',
  maxWidth:500,
  height:'auto',
  backgroundColor:'rgba(0,0,100,0.08)',
  marginTop:20,
  alignSelf:'center',
  paddingVertical:10
 },
 FilterPageUniHeaderContainer:{
  flexDirection:'column',
  width:'auto'
 },
 FilterPageUniHeaderNameContainer:{
  paddingHorizontal:15,
  paddingVertical:15
 },
 FilterPageUniHeaderNameText:{
  fontSize:15,
  fontWeight:'500',
  color:'lightblue',
  letterSpacing:0.3
 },
 FilterBothContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  justifyContent:'flex-start',
  paddingLeft:'5%',
  gap:10,
  borderBottomWidth:1.5,
  borderColor:'lightblue',
  borderStyle:'dashed',
  paddingBottom:20
 },
 FilterPageUniHeaderLocationContainer:{
  display:'flex',
  flexDirection:'row',
  alignItems:'center',
  gap:5,
  paddingRight:7,
  borderRightWidth:1.5,
  borderColor:'#888'
 },
 FilterPageUniHeaderLocationImage:{
  width:10,
  height:10,
 },
 FilterPageUniHeaderLocationText:{
  fontSize:10,
  fontWeight:'500'
 },
 FilterPageUniHeaderRatingContainer:{
  display:'flex',
  flexDirection:'row',
  paddingRight:5,
  alignItems:'center',
  borderRightWidth:1.5,
  borderColor:'#888'

 },
 FilterPageUniHeaderRatingImageContainer:{
  flexDirection:'row',
  gap:0,
 },
 FilterPageUniHeaderRateText:{
  fontSize:11,
  fontWeight:'bold',
  paddingLeft:5
 },
 FilterCourseFeesMainContainer:{
  width:'95%',
  alignSelf:'center',
  display:'flex',
  flexDirection:'row',
  justifyContent:'space-between',
  paddingVertical:10,
  borderBottomWidth:1.5,
  borderColor:'lightblue',
  borderStyle:'dashed'
 },
 FilterCourseFeesContainer:{
  gap:8,
  alignItems:'center'
 },
 FilterCourseFeesHeadText:{
  fontSize:15,
  fontWeight:'500',
  color:'#333',
  letterSpacing:1
 },
 FilterCourseFeesText:{
  fontSize:13,
  fontWeight:'500'
 },
 FilterAdmissionContainer:{
  display:'flex',
  flexDirection:'row',
  justifyContent:'flex-start',
  alignItems:'center',
  paddingLeft:'5%',
 },
 filterOptionMainContainer:{
  display:'none',
  width:'100%',
  height:'auto',
  position:'absolute',
  backgroundColor:'rgba(0,0,0,0.9)',
  zIndex:200,
  alignItems:'center',
  justifyContent:'space-around',
  padding:20,
  flexDirection:'row'
 },
 filterOptionContainer:{
  gap:10,
 },
 filterOptionBtnContainer:{
  borderColor:'lightblue',
  borderRadius:10,
  alignItems:'flex-start'
 },
 filterOptionBtnText:{
  fontSize:11,
  fontWeight:'500',
  color:'#cecece',
 }
})

export default styles